# Generated by Django 5.0.2 on 2024-02-18 12:44

import django.core.validators
import django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_category_book_title_slug_alter_book_book_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to=django_app.models.book_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])]),
        ),
    ]
