# Generated by Django 5.0.2 on 2024-02-18 16:22

import django.core.validators
import django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_remove_book_book_file_book_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to=django_app.models.book_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='django_app.author'),
        ),
    ]
