# Generated by Django 5.0.2 on 2024-02-19 14:00

import django.core.validators
import django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_author_alter_book_book_image_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to=django_app.models.book_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
